name: Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: "**/pyproject.toml"
      - name: Install pre-commit packages
        run: pip install .[format] --quiet
      - name: Run pre-commit
        run: pre-commit run --all-files
